### ISSUE TITLE
rename package

### ISSUE THREAD

**Issue by maxheld83** [subugoe/oauni_10_18#21]
Is there a chance that this will be updated to cover more than 10-18 at some point @njahn82 @Ahobert ?

if so, should the repo maybe have a shorter, more general name?

(Would be nice to straighten this out before #7, so that we can stick to the same url).

**Comment by maxheld83** [comment]
how about simply `oadash` (which @njahn82 seems to already be using for the golem app)

**Comment by Ahobert** [comment]
Since it is designed to be supplementary material to the a research article, I do not expect an update to other time frames.

Still, `oadash` sounds also good to me, I would have no objections to this. However, I like the idea of merging, as in #22 even better, but am not sure how complicated that will be.

**Comment by maxheld83** [comment]
yup, agreed.
I'm putting the merging in #22 on the back burner, but I'd like to get around to doing that to have another muggle showcase 🙃.

We can leave this repo name then, and if #22 ever gets done, the whole thing takes that repo name anyway, which is more widely used/starred.
