### ISSUE TITLE
SUB style

### ISSUE THREAD

**Issue by Ahobert** [subugoe/oauni_10_18#4]
add SUB-css to make appearance more recognizable, specific

**Comment by maxheld83** [comment]
unfortunately, this isn't as easy to do as I expected.
The CSS in [subugoetheme](https://github.com/subugoe/subugoetheme) I made for hoad and other sub-packages targets "vanilla" bootstrap.
Shinydashboard is based on [AdminLTE](https://github.com/almasaeed2010/AdminLTE) which adds a bunch of other classes beyond bootstrap, which would have to be targeted.
(Though AdminLTE *is* itself based on bootstrap).
I don't think this is worth the effort, since we're not otherwise using shinydashboard.
I'm closing this as "won't fix" in favor of #14
